name: Terraform

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # This secret contains your service account key JSON

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}  # Ensure this secret exists

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust version as needed

      # Save GCP credentials to a file and set the environment variable
      - name: Create gcloud.json and set GOOGLE_APPLICATION_CREDENTIALS
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcloud.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json" >> $GITHUB_ENV  # Exports variable for the workflow

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json  # Ensure Terraform can access the credentials

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json  # Ensure Terraform can access the credentials
